### ISSUE TITLE
Is the pathifier algorithm applicable on cancer data only?

### ISSUE THREAD

**Issue by ManarRashad** [lanagarmire/lilikoi#6]
I just need to ask if pathifier algorithm is available for cancer data only as my data related to prediabetes as when I used lilikoi package, this error appeared in PDSfun step (Transform metabolites into pathway using Pathifier algorithm)

Error in UseMethod("filter_"): no applicable method for 'filter_' applied to an object of class "character"
Traceback:

1. PDSfun(Metabolite_pathway_table)
2. qvec %>% filter(pathway != "NA") %>% select(Query, HMDB)
3. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
4. eval(quote(`_fseq`(`_lhs`)), env, env)
5. eval(quote(`_fseq`(`_lhs`)), env, env)
6. `_fseq`(`_lhs`)
7. freduce(value, `_function_list`)
8. function_list[[i]](value)
9. filter(., pathway != "NA")
10. filter.default(., pathway != "NA")
11. filter_(.data, .dots = compat_as_lazy_dots(...))

and this affects on the nest steps 
Could anyone help me, please?

**Comment by lanagarmire** [comment]
Hi there,Pathifier works for data with class labels, so not just cancer only.If you don't mind sharing the data, we can better help to see how the error occurs.Thanks.LanaSent from my T-Mobile 4G LTE Device
-------- Original message --------From: ManarRashad <notifications@github.com> Date: 5/31/20  4:41 AM  (GMT-05:00) To: lanagarmire/lilikoi <lilikoi@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [lanagarmire/lilikoi] Is the pathifier algorithm applicable on cancer data only? (#6) 
I just need to ask if pathifier algorithm is available for cancer data only as my data related to prediabetes as when I used lilikoi package, this error appeared in PDSfun step (Transform metabolites into pathway using Pathifier algorithm)
Error in UseMethod("filter_"): no applicable method for 'filter_' applied to an object of class "character"
Traceback:

PDSfun(Metabolite_pathway_table)
qvec %>% filter(pathway != "NA") %>% select(Query, HMDB)
withVisible(eval(quote(_fseq(_lhs)), env, env))
eval(quote(_fseq(_lhs)), env, env)
eval(quote(_fseq(_lhs)), env, env)
_fseq(_lhs)
freduce(value, _function_list)
function_list[i]
filter(., pathway != "NA")
filter.default(., pathway != "NA")
filter_(.data, .dots = compat_as_lazy_dots(...))

Could anyone help me, please?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lanagarmire/lilikoi/issues/6",
"url": "https://github.com/lanagarmire/lilikoi/issues/6",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ManarRashad** [comment]
Thanks a lot for reply.
It is ok to share my data with you.
The first file: 
[annotated_merged_iPOP_hits.txt](https://github.com/lanagarmire/lilikoi/files/4711697/annotated_merged_iPOP_hits.txt)

it gives this error: 
[1] "Over half of the compound IDs could not be matched to our database. Please make sure that correct compound IDs or common compound names are used."

I understand that it can't identify most of metabolite IDs.

The second file that give me the above error:
[annotated_merged_iPOP_hits_HMDB.txt](https://github.com/lanagarmire/lilikoi/files/4711707/annotated_merged_iPOP_hits_HMDB.txt)

By the way, I use the lilikoi_example.ipynb as lilikoi not available on rstudio as I mentioned in other issue.
Hope to help me, thanks in  advance.

**Comment by ManarRashad** [comment]
@lanagarmire Any updates regarding my data ?

**Comment by lanagarmire** [comment]
Please also send us the R code you were trying to run

Yu, can you follow up with this thread and provide an answer?

Thanks
Lana

**Comment by ManarRashad** [comment]
R code for first file:

R code for second file:

**Comment by ManarRashad** [comment]
`

`

**Comment by ManarRashad** [comment]
Here are the codes for first and second file:
[codes_first_second_files.zip](https://github.com/lanagarmire/lilikoi/files/4727541/codes_first_second_files.zip)

by the way, after adjusting something in my previous code:
the 2 files share in this error:
1] "Over half of the compound IDs could not be matched to our database. Please make sure that correct compound IDs or common compound names are used."

Thanks a lot for your help
Look forward to hearing from you soon.

**Comment by lanagarmire** [comment]
Hi,

It sounds like your pathifier issue is fixed? Good.

This error just means that you metabolomics IDs cannot be mapped very well
with the databases. This is a notorious problem of metabolomics.

You may want to check with the core and get other alien names and see if it
can be improved.

Best

**Comment by ManarRashad** [comment]
I will try to use KEGG ID, maybe I get results.
If there are any problems other than this problem, I will return back to you.
Thanks a lot for help.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
